version: '3.8'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: university
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "3307:3306"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: university
      JWT_SECRET: supersecret
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    command: ["node", "index.js"]

volumes:
  db_data:

